- name: adrian
  pose:
    x: 0.0
    y: 0.0
- name: bartholomew 
  pose:
    x: 0.0
    y: 1.0
- name: charlotte
  pose:
    x: 0.0
    y: 2.0
- name: delilah
  pose:
    x: 0.0
    y: 3.0
- name: evangeline
  pose:
    x: 0.0
    y: 4.0
- name: finnegan
  pose:
    x: 0.0
    y: 5.0