- package: controller_manager
  executable: spawner
  arguments:
  - joint_state_broadcaster
  - --controller-manager
  - controller_manager
  - --controller-manager-timeout
  - "20"
- package: controller_manager
  executable: spawner
  arguments: 
  - velocity_controllers
  - --controller-manager
  - controller_manager