<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:macro name="base_visual" params="">
        <visual>
            <origin xyz="0.0 0.0 ${-BASE_MESH_Z_OFFSET}" rpy="0.0 0.0 ${PI/2}"/>
            <geometry>
                <mesh filename = "${MESH_FOLDER}/${BASE_MESH_FILE}"/>
            </geometry>
            <material name="chassis_color">
                <color rgba="${BASE_COLOR}"/>
            </material>
        </visual>
    </xacro:macro>

    <xacro:macro name="base_offset" params="namespace">
        <joint name="${namespace}/base_offset" type="fixed">
            <parent link="${namespace}/base_footprint"/>
            <child link="${namespace}/base_link"/>
            <origin xyz="0.0 0.0 ${BASE_HEIGHT/2+BASE_ELEVATION}"/>    
        </joint> 
    </xacro:macro>

    <xacro:macro name="chassis_visual" params="namespace">
        <link name="${namespace}/base_footprint"/>
        <link name="${namespace}/base_link">
            <xacro:base_visual/>
        </link>
        <xacro:base_offset namespace="${namespace}"/>
    </xacro:macro>
</robot>
